function setOrder(objects) {
  objects.forEach((obj, index) => {
    obj.id = (index + 1).toString();
  });
}

const storeData = [
 
 

  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 101 ,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 199 ,
    feature: true,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 100,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 101,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 102,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 120,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 89,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "A2S19",
    type: "Shirt",
    price: 55,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    brand : "A2S19",
    type: "Shirt",
    price: 111,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "A2S19",
    type: "Shirt",
    price: 99,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "A2S19",
    type: "Shirt",
    price: 93,
    isAddToCart: false,
  },
  
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "A2S19",
    type: "Shirt",
    price: 90,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 78,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "A2S19",
    type: "Shirt",
    price: 89,
    isAddToCart: false,
  },
 {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    brand : "AAKs",
    type: "Shirt",
    price: 23,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    brand : "AAKs",
    type: "Shirt",
    price:  34,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "A2S19",
    type: "Shirt",
    price: 67,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 124,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "AAKs",
    type: "Shirt",
    price: 65,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AAKs",
    type: "Shirt",
    price: 78,
    feature: true,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "AAKs",
    type: "Shirt",
    price: 99,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "AAKs",
    type: "Shirt",
    price: 67,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "AAKs",
    type: "Shirt",
    price: 67,
    isAddToCart: false,
  },

  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 56,
    isAddToCart: false,
  },
  
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 85,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 88,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 99,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 91,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
 
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 94,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 97,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "HELLY",
    type: "Shirt",
    price: 69,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 78,
    feature: true,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 99,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 133,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 99,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 109,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 55,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 99,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 99,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 99,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 99,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 66,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    brand : "Ak019",
    type: "Shirt",
    price: 69,
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    brand : "AKING",
    type: "Shirt",
    price: 99,
    isAddToCart: false,
  },
];
setOrder(storeData);

export default storeData;
