function setOrder(objects) {
  objects.forEach((obj, index) => {
    obj.id = (index + 1).toString();
  });
}

const storeData = [
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },

  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts1.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },

  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    feature: true,
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts2.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    option: {
      color1: "Black",
      color2: "Blue",
      color3: "Red",
      color4: "White",
      color5: "Brown",
    },
  },
  {
    image: "images/Store/shirts5.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts3.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
  {
    image: "images/Store/shirts4.jpeg",
    intro: "Mens Shirts",
    type: "Shirt",
    price: "119 ",
    isAddToCart: false,
  },
];
setOrder(storeData);

export default storeData;
